### ISSUE TITLE
파일 다운로드시 확장자명에 세미콜론이 붙는 현상 발생

### ISSUE THREAD

**Issue by jin3811** [Hansung-Notification/Hansung_Android#40]
발생 기기 : SM-A826S (갤럭시 퀀텀 2)

확장자명에 세미콜론이 같이 붙어서 다운로드되는 현상 발생.

![image](https://user-images.githubusercontent.com/66506964/182069911-df02ef03-72bd-4081-b890-41091252af2f.png)
![image](https://user-images.githubusercontent.com/66506964/182069919-de81d831-e9e2-4278-b103-f0526ef14958.png)

**Comment by jja08111** [comment]
안녕하세요 @jin3811 님, 이슈를 보고해주셔서 감사합니다. 

문제에 대해 확인 하였으며 추후 수정 후 앱을 업데이트 하겠습니다. 

감사합니다.

**Comment by jin3811** [comment]
같은 한성대 학우로써 미약하게나마 도움이 되어 다행입니다
